### ISSUE TITLE
Not available on App Store

### ISSUE THREAD

**Issue by ishan-chhabra** [MSPC-Tech/MentalHealthApp#5]
## Expected Behaviour
The app should be available across all major platforms to make it accessible for everyone

## Actual Behaviour
The app is not available on the App Store

**Comment by shantnu-agarwal** [comment]
@ishan-chhabra Great, thanks!

**Comment by ishan-chhabra** [comment]
Glad I could help out!
Go nuts: https://apps.apple.com/us/app/id1523215331
